[package]
name    = 'sh-elf-vhex'
version = '1.0.1'
type    = 'app'

[build]
configure = 'make -f giteapc.make configure'
build     = 'make -f giteapc.make build'
install   = 'PREFIX=$VXSDK_INSTALL_PREFIX make -f giteapc.make install'
uninstall = 'PREFIX=$VXSDK_INSTALL_PREFIX make -f giteapc.make uninstall'
