[project]
name    = 'sh-elf-vhex'
version = '1.0.3'
type    = 'app'

[build]
configure = 'make configure'
build     = 'make build'
install   = 'PREFIX=$VXSDK_PREFIX_INSTALL make install'
uninstall = 'PREFIX=$VXSDK_PREFIX_INSTALL make uninstall'
